version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running pre-build checks...
      - python -m unittest discover -s tests || echo "Tests failed but continuing"

  build:
    commands:
      - echo Starting training script...
      - python train_model.py

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Saving model artifacts...

artifacts:
  files:
    - model/*
    - logs/*
    - output/*
  discard-paths: no
